### ISSUE TITLE
Provide version compatibility matrix

### ISSUE THREAD

**Issue by holgerstolzenberg** [openshift/ocs-operator#1012]
We recently had to reinstall the OCS operator to our OKD 4.6 cluster after a full uninstall of the operator.
The version that was removed and working with the cluster was OCS 4.6.0

Reinstalling the operator via Operator Hub UI points to latest so OCS 4.8.0 was installed but could never fully complete.

Should the cluster version correlate to the OCS version and the operator be installed via OLM? Or should OCS 4.8 work on a 4.6 cluster.

Please provide some more documentation on that or a version compatibility matrix in the README.

**Comment by jarrpa** [comment]
This repo is not the right place for hosting that information. Official product compatibility information is hosted in official Red Hat websites and documentation. If you can't find that information you should submit the question via official Red Hat channels.
