### ISSUE TITLE
Rook v1.1.0-beta.2 requirement tracker.

### ISSUE THREAD

**Issue by rohantmp** [openshift/ocs-operator#105]
Rook beta 2 is not yet released. This issue is for tracking what has to change when we use it for a release. Most of bugfixes are features we're waiting for and need to test.

- PG autoscaler: https://github.com/rook/rook/pull/3769

**Comment by petr-balogh** [comment]
@rohantmp  do I understand correctly that it depends on the new tag in in rook v1.1.0-beta.2 appear in rook? Once done, some change in operator needs to be done as well, or nothing needs to be done and it's enabled by default?  Any time estimation when we can see this pg autoscaler enabled by operator? Thanks

**Comment by travisn** [comment]
With the `v1.1.0-beta.1` tag created, the pg autoscaler can now be created as mentioned [here](https://rook.io/docs/rook/master/ceph-configuration.html)
```yaml
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
```
@rohantmp Or is there another requirement you're looking for in beta.2?

**Comment by rohantmp** [comment]
Yup, other than the bugfix: https://github.com/rook/rook/pull/3786 that's all so far.

**Comment by rohantmp** [comment]
Oh, I misread that. I see that this can be done in beta.1 closing this issue.
