### ISSUE TITLE
Update client-go

### ISSUE THREAD

**Issue by mulbc** [openshift/ocs-operator#1124]
https://github.com/openshift/ocs-operator/blob/4803a10dce0199efe39f92720d01c807ab2e5cff/go.mod#L31

The referenced client-go version is very out of date. Please update it

**Comment by jarrpa** [comment]
You're better off filing a BZ, we don't track GitHub issues.

**Comment by rohantmp** [comment]
client-gov12 is the latest release, you're probably thinking of k8s api libs which are at v20: https://github.com/openshift/ocs-operator/blob/4803a10dce0199efe39f92720d01c807ab2e5cff/go.mod#L28
