### ISSUE TITLE
starting toolbox pod from ansible playbook

### ISSUE THREAD

**Issue by bengland2** [openshift/ocs-operator#1177]
I tried to [start ceph toolbox pod from an ansible playbook as shown in this pastebin, and I get 403 priv violation](https://pastebin.com/VRTWVUh7).   So what privs do I need to be able to do this?   I can do it from shell with oc, why is this different?  is it because from shell I'm logged in as admin, as shown in $KUBECONFIG, whereas from my benchmarking software, the playbook is not logged in as cluster admin?   What is the minimum privilege needed to do this action?  Or is there some secret I can utilize?  Sorry for the newbie question, security isn't my thing.

background: I am trying to add support to benchmark-operator for dropping cache in Ceph OSDs, but I can't do this without the toolbox pod, where I can issue "ceph tell osd.* cache drop" .

My workaround would be to have the user start the Ceph toolbox, then run the benchmark, but I'd rather automate it if possible for use in CI.

**Comment by jarrpa** [comment]
GitHub is not a good place for such inquiries. You should either go into chat rooms or mailing lists.

**Comment by bengland2** [comment]
fair enough, will close this out.
