### ISSUE TITLE
Missing toleration for master nodes in install documentation 

### ISSUE THREAD

**Issue by siwyroot** [openshift/ocs-operator#1181]
Hello,

Compliance Operator cannot run on OpenShift Container Storage as it's missing toleration for master nodes. I think  install docs need to be updated to include that or operator should include this by default.At this moment attaching PVC to master node fails with following error:

MountVolume.MountDevice failed for volume "pvc-04cce714-b99e-439f-b593-de260050e5b9" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name openshift-storage.cephfs.csi.ceph.com not found in the list of registered CSI drivers

Issue opened for compliance operator:
https://github.com/openshift/compliance-operator/issues/642

Could someone guide me how I can modify already deployed OCS cluster to include that toleration?

**Comment by jarrpa** [comment]
Closing this as a duplicate of #1180
