### ISSUE TITLE
must-gather pod fails to fetch jq in a disconnected/restricted network cluster

### ISSUE THREAD

**Issue by naveedahd** [openshift/ocs-operator#1187]
While working for a client in a disconnected OCP 4.6 with OCS 4.6 cluster, the helper pod fails to fetch `jq` from the internet because it has no external connection. It precisely fails on the following:

https://github.com/openshift/ocs-operator/blob/38b9d53f6f0e2441883f9551b7fdbd2c361d7da6/must-gather/collection-scripts/gather_ceph_resources#L104

The error looks like this:

```
[must-gather-hgqj6] POD helper pod got deployed successfully.
[must-gather-hgqj6] POD --2021-05-22 17:33:45-- http://stedolan.github.io/jq/download/linux64/jq
[must-gather-hgqj6] POD Resolving stedolan.github.io (stedolan.github.io)... 185.199.109.153, 185.199.108.153, 185.199.110.153, ...
[must-gather-hgqj6] OUT gather logs unavailable: unexpected EOF
[must-gather-hgqj6] OUT waiting for gather to complete
```

What can we do to remediate this? We can edit the scripts on the pod and make it fetch `jq` from a local hosted source but that'll be too hacky to do every time.

**Comment by jarrpa** [comment]
Hmm, that's a tricky one... we could try and just bake it into the must-gather container image? @crombus @rajatsing thoughts?

**Comment by crombus** [comment]
> Hmm, that's a tricky one... we could try and just bake it into the must-gather container image? @crombus @rajatsing thoughts?

I don’t remember the exact issue what I was having trouble getting the jq in must-gather container image. That is why we did this way.

Seeing this issue I asked @Madhu-1 for a cmd using without jq 
```ceph fs subvolume ls myfs --group_name=csi| awk '/name/ { gsub(/[",]/,"",$2); print $2}'```

We can try this.

**Comment by Madhu-1** [comment]
`jq` is one of the best options to parse the json outputs. As @jarrpa suggested we should have `jq` pre-installed in must-gather container image , If we need alternatives We can check with @nixpanic @agarwal-mudit for better commands

**Comment by nixpanic** [comment]
We definitely should not download anything from GitHub (or other non stable internet locations) during runtime.

I am not sure what the source for the `"${HOSTNAME}"-helper` container is, but it should be possible to install `jq` from a verifiable source (standard OS repository with `dnf`). It seems Ceph tools are included, so including other packages should not be too difficult?

**Comment by rajatsing** [comment]
@nixpanic `"${HOSTNAME}"-helper` is the name of the must-gather helper pod, we save the prefix in the `$HOSTNAME`  variable.

**Comment by nixpanic** [comment]
> @nixpanic `"${HOSTNAME}"-helper` is the name of the must-gather helper pod, we save the prefix in the `$HOSTNAME` variable.

Yes, I understand that. But I would like to know what container image is used by this helper pod. We should be able to add `dnf -y install jq` in the `Containerfile` for the image that already contains the installing of Ceph tools. @rajatsing, can you point me to the source of the image?

**Comment by rajatsing** [comment]
From what I understand, this is the command that we use to run must gather `oc adm must-gather --image=quay.io/ocs-dev/ocs-must-gather`, notice the image name is `quay.io/ocs-dev/ocs-must-gather` and this the  [YAML](https://github.com/openshift/ocs-operator/blob/master/must-gather/templates/pod.template.latest)  that creates this image above

**Comment by rajatsing** [comment]
Otherwise, this [YAML](https://github.com/openshift/ocs-operator/blob/master/must-gather/templates/pod.template.standard) is being used if the OCS version is < 4.6

**Comment by nixpanic** [comment]
@rajatsing sorry, those links do not point to the source of the `quay.io/ocs-dev/ocs-must-gather` container image, but to a spec that deploys/starts a Pod with that image. Can you point to scripts that build the container image?

**Comment by rajatsing** [comment]
@nixpanic I will give you a complete rundown below.

- we run `make ocs-must-gather` command to start the script that will build the container image, [this is where it begins](https://github.com/openshift/ocs-operator/blob/master/Makefile#L74-L76)

- The script that makes the container image is [this ](https://github.com/openshift/ocs-operator/blob/fb10214988229a83dce75b452f2135cc8e78a088/hack/build-must-gather.sh) which uses this [Dockerfile](https://github.com/openshift/ocs-operator/blob/master/must-gather/Dockerfile)  which points to the [YAMLs](https://github.com/openshift/ocs-operator/tree/master/must-gather/templates) that I posted above.

**Comment by nixpanic** [comment]
@rajatsing I'm still a bit confused. The `Dockerfile` seems to use `quay.io/openshift/origin-cli:latest` as a base image. But, the collection scripts call the `ceph` command, which is not part of that image. Where does the Ceph command get installed?

```
$ podman run --rm -ti quay.io/openshift/origin-cli:latest
[root@1ee42194aa2f /]# which ceph
/usr/bin/which: no ceph in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

And the Ceph tools are clearly not available in the ocs-must-gather image either:

```
$ podman run --rm -ti --entrypoint=/bin/bash quay.io/ocs-dev/ocs-must-gather 
[root@476059db40a2 /]# which ceph
/usr/bin/which: no ceph in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

How can the [ceph resource gather](https://github.com/openshift/ocs-operator/blob/master/must-gather/collection-scripts/gather_ceph_resources) commands ever get executed in the `${HOSTNAME}-helper` pod?

The goal is to get `jq` added to the container image where the Ceph commands are running. Further pointers to that would be very helpful.

**Comment by rajatsing** [comment]
@crombus can you please clarify this?. Seems like I am missing something but couldn't recall.

**Comment by crombus** [comment]
Hey @nixpanic ,

https://github.com/openshift/ocs-operator/blob/master/must-gather/Dockerfile. 
This must-gather image container.
Helper-pod is ceph-toolbox managed by must-gather. Different pod running in openshift-storage ns.

must-gather scripts run in ceph-toolbox (helper-pod)

As you pointed out it uses ```quay.io/openshift/origin-cli:latest```

this is the reason we install jq through wget.

**Comment by crombus** [comment]
I guess we can do multistage builds to solve the issue. 

@jarrpa @rajatsing

**Comment by nixpanic** [comment]
Thanks @crombus! In that case, we might be able to get `jq` added to the ceph-toolbox container image (rook/rook#7989).
