### ISSUE TITLE
OCS CatalogSource Pod uses invalid image name

### ISSUE THREAD

**Issue by Feelas** [openshift/ocs-operator#132]
--- Bug description ---
Sometimes while deploying, the CatalogSource pod responsible for serving the OCS Operator to the cluster, ends up with an improper image name and refuses to start because of that.

The incorrect image name is `Image: quay.io//ocs-registry:latest`. The behaviour happens because the ocs-dev part in `Image: quay.io/ocs-dev/ocs-registry:latest` gets cut, somehow. When ocs-dev is put into place, the installation process continues and both Local Storage Operator and OCS Operator get installed.

--- How to reproduce ---
I didn't manage to get a reproducible way to trigger the bug, however, some versions of deployment image do not cause that to happen - that part seemed to work fine with v0.0.1-alpha.1-15-g45140f3 and v0.0.1-alpha.1-21-gf63c4b3 images.

--- Expected behaviour ---
The image of pod will be set to `Image: quay.io/ocs-dev/ocs-registry:latest` and the operator will successfully install itself.

**Comment by kshlm** [comment]
The CatalogSource is defined in [deploy-with-olm.yaml](https://github.com/openshift/ocs-operator/blob/e59ca0fd6ba80cbb8d8dfa6db0b1373dd610c7a1/deploy/deploy-with-olm.yaml#L31-L41). As you see, it has the correct image name. This file is not generated, like the CSV, so there is no reason to have the image be missing a part.

Can you explain how you went about creating the CatalogSource?

**Comment by Feelas** [comment]
It's also puzzling to me, seeing everything declared inside deployment .yaml and then seeing something strange happening to the image. Possibly this is not connected to an OCS Operator bug itself and a bug somewhere else.

It just happens sometimes when doing `oc create -f deploy/deploy-with-olm.yaml`, just as the installation tutorial specifies.

**Comment by rohantmp** [comment]
@Feelas Is this still happening?

**Comment by Feelas** [comment]
@rohantmp Seems not to happen with current releases, I believe it's a bug in something entirely different than the operator itself and this should be closed, maybe just something to check if it happens in the future.
