### ISSUE TITLE
Nodes tainted with 'node.ocs.openshift.io/storage=true:NoSchedule' by default

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/ocs-operator#156]
I'm running UAT for OCS-Operator 4.2 (master) on a OCP 4.2.0-0.ci-2019-09-25-072821, deploying through OLM (`oc create -f ocs-operator/deploy/deploy-with-olm.yaml`) and creating the `Storage Cluster` using UI but multiple pods are not being scheduled.

Checking the logs, it points to taint applied to the worker nodes (the ones I choose using UI) of `node.ocs.openshift.io/storage=true:NoSchedule` leaving the pods with errors such as `0/6 nodes are available: 6 node(s) had taints that the pod didn't tolerate.`. 

The problem seems to be fixable removing the taint from the nodes with `oc adm taint node <workers> node.ocs.openshift.io/storage:NoSchedule-`

**Comment by jarrpa** [comment]
This is the currently expected behavior. We are in discussions to see what we will want to do about it.

**Comment by davivcgarcia** [comment]
>     * If the pods are OCS pods, then it's a bug and they need to get the taints. The deployment should succeed even if there are only 3 (worker) nodes, all of which are tainted.

This is my case. The OCS pods are also affected.

**Comment by umangachapagain** [comment]
Tainting by default has been removed. Changes went into OpenShift/Console. This issue can be closed.

**Comment by obnoxxx** [comment]
Additionally, the tolerations should now be set such that also with the edge case of only tainted nodes, deployment should succeed.
