### ISSUE TITLE
panic: error converting YAML to JSON: yaml: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by b-ranto** [openshift/ocs-operator#186]
We are hitting a panic when generating the unified CSV with the latest noobaa images (v2.0.1) and the latest master:

```
+ make gen-release-csv
Generating unified CSV from sourced component-level operators
hack/generate-unified-csv.sh
reading in csv at build/_output/csv-templates/ocs-operator.csv.yaml.in
reading in csv at build/_output/csv-templates/rook-csv.yaml.in
reading in csv at build/_output/csv-templates/noobaa-csv.yaml
panic: error converting YAML to JSON: yaml: mapping values are not allowed in this context

goroutine 1 [running]:
main.unmarshalCSV(0x7ffec3218d08, 0x2b, 0x0)
	/home/jenkins-build/build/workspace/ocs-operator-containers/github/tools/csv-merger/csv-merger.go:128 +0x38b
main.generateUnifiedCSV()
	/home/jenkins-build/build/workspace/ocs-operator-containers/github/tools/csv-merger/csv-merger.go:371 +0x14c0
main.main()
	/home/jenkins-build/build/workspace/ocs-operator-containers/github/tools/csv-merger/csv-merger.go:683 +0x1d3
make: *** [Makefile:97: gen-release-csv] Error 2
```

It looks like this is related to noobaa since it fails at `noobaa-csv.yaml`, @guymguym can you also take a look at this?

**Comment by guymguym** [comment]
I can check but much later today.
@dannyzaken or @davidvossel can you get more info on the failure?

**Comment by b-ranto** [comment]
I have done some debugging, the generation fails at this function:

https://github.com/openshift/ocs-operator/blob/master/tools/csv-merger/csv-merger.go#L104

I have added some debugging output and the writer.String() in that function returns:
`writer.String: /usr/local/bin/entrypoint: line 12: /usr/local/bin/noobaa-operator: No such file or directory`

That is also all that `noobaa-csv.yaml` contains:
`/usr/local/bin/entrypoint: line 12: /usr/local/bin/noobaa-operator: No such file or directory`

It looks like the csv generation failed because of that. Running the command manually, it looks like the latest downstream noobaa operator because it points to an invalid entrypoint.

Inspecting the ds `noobaa-operator`, I don't see any `noobaa-operator` binary in it (`find / | grep noobaa-operator` returns nothing).

Looking at the downstream Dockerfile, it is only running `CGO_ENABLED=0 GO111MODULE=on go build -mod=vendor` to build the binaries and just copying the entire `build/bin` to `/usr/local/bin`. That means that the `noobaa-operator` is not being built by default.

All in all, this is definitely an issue on noobaa side of the things.

**Comment by guymguym** [comment]
Thanks @b-ranto !
@nimrod-becker Lets ask the team to verify the ds build.

**Comment by liranmauda** [comment]
@b-ranto 
We have found an issue in our downstream build and it is now fixed.

Thanks

**Comment by b-ranto** [comment]
The builds are passing, now -> closing.
