### ISSUE TITLE
RGW is not started after a StorageCluster is created

### ISSUE THREAD

**Issue by dannyzaken** [openshift/ocs-operator#191]
### problem description

1. I created a `StorageCluster` using the example cr in ocs-operator repo - https://github.com/openshift/ocs-operator/blob/master/deploy/crds/ocs_v1_storagecluster_cr.yaml

2. the operator created a `CephObjectStore` resource, which looks like it's invalid (all values are 0)

resource yaml:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  creationTimestamp: 2019-10-07T07:58:28Z
  generation: 1
  name: example-storagecluster-cephobjectstore
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: ocs.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: StorageClusterInitialization
    name: example-storagecluster
    uid: 3eeac13e-e8d8-11e9-b1de-005056beac7f
  resourceVersion: "5527795"
  selfLink: /apis/ceph.rook.io/v1/namespaces/openshift-storage/cephobjectstores/example-storagecluster-cephobjectstore
  uid: 3f27dd1c-e8d8-11e9-b1de-005056beac7f
spec:
  dataPool:
    crushRoot: ""
    deviceClass: ""
    erasureCoded:
      algorithm: ""
      codingChunks: 0
      dataChunks: 0
    failureDomain: ""
    replicated:
      size: 0
  gateway:
    allNodes: false
    instances: 1
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cluster.ocs.openshift.io/openshift-storage
              operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-rgw
            topologyKey: kubernetes.io/hostname
          weight: 100
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    port: 80
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securePort: 0
    sslCertificateRef: ""
  metadataPool:
    crushRoot: ""
    deviceClass: ""
    erasureCoded:
      algorithm: ""
      codingChunks: 0
      dataChunks: 0
    failureDomain: host
    replicated:
      size: 3
```

3. RGW is never created

### Steps to Reproduce:
1. create a storage cluster
2. `oc get cephobjectstore -o yaml`
3. see the created resource 

### Actual results
created CephObjectStore looks invalid and RGW is not started

### Expected results:
RGW should be started (at least for vmware deployents)

**Comment by jarrpa** [comment]
@dannyzaken We need someone with more familiarity with RGW to determine what the right values would be. Do you or someone you know have the time to look into this?

**Comment by guymguym** [comment]
@mattbenjamin

**Comment by dannyzaken** [comment]
@jarrpa, unfortunately, I don't have enough familiarity with RGW, so I can't tell what the right values are.

**Comment by guymguym** [comment]
@travisn can help?

**Comment by travisn** [comment]
The replication size on the data pool should be the same as the metadata pool (assuming we're using replication and not erasure coding). The problem is that data replication is currently set to 0. 
```
    replicated:
      size: 3
```

**Comment by travisn** [comment]
The rook operator likely has an error in the logs that indicates it's an invalid object store for this reason, which is why it didn't start the rgw service.

**Comment by guymguym** [comment]
Many thanks @travisn !
