### ISSUE TITLE
Installing OCS on Openshift 4.2 pre release cluster

### ISSUE THREAD

**Issue by deevya2000** [openshift/ocs-operator#200]
How do you create a storagecluster for bare metal openshift cluster using ocs operator ? I have installed the operators using:

oc create -f ./deploy/deploy-with-olm.yaml

 but the sample yaml to create storage cluster in the next step has a type : gp2 which is for AWS I guess, which I tried and it failed..I need to do it for a bare metal openshift 4.2 cluster..any thoughts ?

I have a 3 master and 3 node configuration and I have labelled the worker nodes as storage nodes. I am expecting a CNS type of installation (I have installed GlusterFS CNS on Openshift 3.11 before) using local storage from worker nodes. Please let me know how to accomplish this using the ocs operator

**Comment by jarrpa** [comment]
As we discussed on the Kubernetes Slack, as of OCS 4.2 there is no plan to support OCS outside of a paid OCS subscription. Keep an eye on the [Red Hat Storage blog channel](https://www.redhat.com/en/blog/channel/red-hat-storage) for more official announcements on our timelines and support statements.
