### ISSUE TITLE
rfe: support for disconnected installations

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/ocs-operator#217]
We are running a disconnected intallation and would like to use the ocs operator. 

I tried changing the image versions in the OLM config but it still keeps referring to images hosted elsewhere and the images used in this operator are alse tag based instead of manifest based so using the new cluster imagecontent resource is not possible at this time.

**Comment by jamescassell** [comment]
Here's what's needed: https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

**Comment by umangachapagain** [comment]
Fixed in release-4.4.
Updated documentation: https://github.com/openshift/ocs-operator/pull/542
