### ISSUE TITLE
Allow creation of clusters with less than 3 nodes

### ISSUE THREAD

**Issue by mulbc** [openshift/ocs-operator#311]
https://github.com/openshift/ocs-operator/blob/9a55e5215b6eca397960c180d0cb32c1983c6285/pkg/controller/storagecluster/reconcile.go#L337-L342

Due to the < comparison with `defaults.DeviceSetReplica` (which is 3), it is not possible to deploy OCS on an environment with less than three nodes.
Please remove this hard limitation in order to allow demos in smaller deployments. I need this for Katacoda

**Comment by mykaul** [comment]
I honestly don't know how OCS will behave with less than 3 nodes.

**Comment by jarrpa** [comment]
It definitely could be done, but this is not something we'll be getting around to any time soon. Certainly not before OCS 4.2 GA and probably not for 4.3.

**Comment by mulbc** [comment]
@travisn Could you please point me to the code that I would need to change to create just a single MON and set pools to replica 1?
I already started a fork where I set the default DeviceSetReplica to 1, so I could host the changes over there until you're ready to merge. That way I can use my fork in Labs like Katacoda

**Comment by mulbc** [comment]
Closing since I have had my fork for a while now already - it works perfectly (and is now ~1 year old code)
