### ISSUE TITLE
Add more resources to RGW

### ISSUE THREAD

**Issue by mykaul** [openshift/ocs-operator#334]
RGW needs more resources. What we are giving to it right now is simply not enough for reasonable performance:
https://github.com/openshift/ocs-operator/blob/2c257dfcf8f205d1011c08a8c6ef6b6a49433648/pkg/controller/defaults/resources.go#L42
```
		"rgw": corev1.ResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("1"),
				corev1.ResourceMemory: resource.MustParse("2Gi"),
			},
```

I'd change it to 2 CPUs and 4G.

**Comment by jarrpa** [comment]
This was resolved in master, and is not needed for 4.2. Resolving this issue.
