### ISSUE TITLE
Create a shellcheck test script to run in ocs-operator-ci.

### ISSUE THREAD

**Issue by obnoxxx** [openshift/ocs-operator#341]
We need a test to ensure our shell scripts are syntactically correct and safe.
Some `bash -n` is a basic syntax check, but `shellcheck` is much more comprehensive.

The test should be a Makefile target, and should be executed in the CI (ocs-operator-ci).

Examples can be found here: https://github.com/heketi/heketi, specifically https://github.com/heketi/heketi/blob/master/tests/020-test-shellscripts.sh.

**Comment by jarrpa** [comment]
@crombus Is interested in taking this up.

**Comment by crombus** [comment]
closing the issue as thr pr got merged
