### ISSUE TITLE
Using storagecluster along with local storage

### ISSUE THREAD

**Issue by karmab** [openshift/ocs-operator#35]
Currently, a single storage class is specified in a storagecluster definition and used for both mon and osd pvcs.
Mon pvcs have a filesystem volume mode, while osds ones have volume mode set to block.

That doesn't fit the use of local volumes since in this case, the corresponding storage classes can only provision pvcs from a single volume mode.
 
The storage cluster should have an extra field to point to a different storage class for the mon pvcs or have a way for the deployment to be done without those mon pvcs.

**Comment by kshlm** [comment]
Thanks for opening this. We had a discussion before I added to code to create mon PVs based on the OSD pvs. We decided on this approach with the assumption that it was okay for now on AWS, and we'd add proper support for setting the PV later on.

But I didn't expect the later on to come so soon.

**Comment by kshlm** [comment]
@jarrpa @travisn I'll take up implementing this, and this is what I propose to do.

- Add a new member `MonPVCTemplate` to the StorageCluster spec, and keep it optional.
- If defined, I'll use the `MonPVCTemplate` in the CephCluster object created.
- If not, I'll follow the current strategy of using the first StorageDeviceSet.

Is this okay with you guys?

**Comment by jarrpa** [comment]
That should work, yeah.

**Comment by kshlm** [comment]
#48 fixes this.
