### ISSUE TITLE
OCP CI build uses a different base image than the operator uses?

### ISSUE THREAD

**Issue by mykaul** [openshift/ocs-operator#369]
It seems that the build we use in OCP CI is using:
```
FROM registry.access.redhat.com/ubi7/ubi-minimal:latest
```
(https://github.com/openshift/ocs-operator/blob/e6b769f821180f7d40bc64532e1f5116b7876775/openshift-ci/Dockerfile.deploy)
And when we build the OCS operator regularly, we use:
```
FROM registry.access.redhat.com/ubi8/ubi-minimal
```
(https://github.com/openshift/ocs-operator/blob/ab4540d76e824c8525f80340b6f63982ff44251f/build/Dockerfile )

**Comment by kshlm** [comment]
IIRC, when the CI dockerfile was created, we were facing some issues with getting the ubi8 image available in the CI cluster. @davidvossel might remember better. 

This was before we started building and pushing the upstream images using openshift-ci. And it seems those images, which are built from the non-ci dockerfile, are getting built correctly. So we can move back to ubi8.
