### ISSUE TITLE
CSV should set env var of downstream image names on noobaa-operator deployment

### ISSUE THREAD

**Issue by guymguym** [openshift/ocs-operator#372]
This is needed because otherwise the noobaa-operator cannot tell which downstream images to use when used from mig-operator.

**Comment by guymguym** [comment]
CC @nimrod-becker

**Comment by obnoxxx** [comment]
@jackyalbo @nimrod-becker @guymguym - now that #381 is merged, can this be closed?

**Comment by guymguym** [comment]
Yes, closing
