### ISSUE TITLE
Bump deps to operator-sdk v0.15.0 and controller-runtime v0.4.0

### ISSUE THREAD

**Issue by guymguym** [openshift/ocs-operator#391]
https://github.com/operator-framework/operator-sdk/releases/tag/v0.13.0
https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.4.0

This is to allow using features from kubernetes 1.16.
CC @travisn

**Comment by mykaul** [comment]
operator-sdk has released a newer version just few days ago - https://github.com/operator-framework/operator-sdk/releases/tag/v0.14.0
Worth looking at it?

**Comment by guymguym** [comment]
@mykaul Sure. I didn't see in the 0.14 changelog anything I waited for in particular, but it's best to bump whenever possible.

**Comment by nimrod-becker** [comment]
@jarrpa Talked to Michael, he suggested we'd start a thread with you on this one

**Comment by jarrpa** [comment]
@nimrod-becker sure. Chat or email would be better. 🙂

**Comment by obnoxxx** [comment]
Yeah, that's what I meant. I think this is reasonable to do now that 4.2 is out.

**Comment by jarrpa** [comment]
I should be able to take this on next week!
