### ISSUE TITLE
Set mon clock drift allowed in rook-config-override

### ISSUE THREAD

**Issue by gorantornqvist** [openshift/ocs-operator#407]
Getting this warning:
```
  cluster:
    id:     b7822581-efc6-44fa-a462-b0d0f42f21a6
    health: HEALTH_WARN
            clock skew detected on mon.b, mon.c
```
So I would like to increase the allowed drift a bit in rook-config-override configmap:
```
apiVersion: v1
data:
  config: |
    [global]
    mon clock drift allowed = 0.5
kind: ConfigMap
```
But the ocs-operator removes that setting:
```
{"level":"info","ts":1581326395.8172352,"logger":"controller_storagecluster","msg":"Updating Ceph ConfigMap","Request.Namespace":"openshift-storage","Request.Name":"ocs-storagecluster"}
```
Is there a way to set this?

**Comment by xenolinux** [comment]
@gorantornqvist for how long have you observed this warning? was it went for some minutes/hours and cleared automatically? Is your machine synched with the NTP server?

**Comment by gorantornqvist** [comment]
When it occurred I observed it for a few hours, I checked NTP on the nodes the mon pods were running on and they were synced ok.
I then restarted both the mon pods manually and after a few minutes the alerts cleared.
I havent seen the alerts since then so it appears to have been a temporary issue so maybe this override isnt needed ...

**Comment by xenolinux** [comment]
Cool
