### ISSUE TITLE
ocs-operator gets stuck on crashloopbackoff

### ISSUE THREAD

**Issue by chechuironman** [openshift/ocs-operator#426]
hey guys,

I'm getting this error on the ocs-opoerator pod:

`{"level":"info","ts":1582754843.4522314,"logger":"cmd","msg":"Go Version: go1.11.13"}
{"level":"info","ts":1582754843.4522955,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1582754843.4523048,"logger":"cmd","msg":"operator-sdk Version: v0.10.0"}
{"level":"info","ts":1582754843.4527922,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1582754845.7318735,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1582754845.7319334,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1582754847.9910502,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1582754847.991344,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1582754847.992188,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"ocsinitialization-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1582754847.9924538,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"storagecluster-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1582754847.9926023,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"storagecluster-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1582754847.9927535,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"storagecluster-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1582754847.9933817,"logger":"cmd","msg":"Failed to create OCSInitialization custom resource","error":"an empty namespace may not be set during creation","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/openshift/ocs-operator/cmd/manager/main.go:139\nruntime.main\n\t/opt/rh/go-toolset-1.11/root/usr/lib/go-toolset-1.11-golang/src/runtime/proc.go:201"}
`
any idea?

**Comment by umangachapagain** [comment]
Use only `openshift-storage` namespace to install operator and cluster. That should fix this.

**Comment by jarrpa** [comment]
Since a recommendation has been made and it's been more than two weeks since the last message, I'll be closing this issue. Please reopen if the problem persists.
