### ISSUE TITLE
[ROKS] Support for ROKS storage classes

### ISSUE THREAD

**Issue by akgunjal** [openshift/ocs-operator#455]
OCS should recognize and create remote volume using ROKS storage classes.

**Comment by jarrpa** [comment]
There should be no special development needed for the StorageClasses themselves. As of OCS 4.3, you will be able to select which StorageClass to base your volumes on from the StorageCluster creation screen. If there are any issues with creating OSDs on PVs provided by ROKS StorageClasses, those deserve their own issue. Closing this one for now.
