### ISSUE TITLE
[ROKS] Support for local disks without using local persistent volumes

### ISSUE THREAD

**Issue by akgunjal** [openshift/ocs-operator#456]
Currently we use local disks wrapped with local persistent volumes. OCS needs to support for local disks without using local persistent volumes. Ideally the OCS storage cluster needs to accept the local disk (ex: `/dev/sdc`) as input so local volumes are not needed.

**Comment by travisn** [comment]
Per discussion, it is recommended to use the local storage operator and create a LocalVolume CR for a device. OCS does not support directly using devices without a PV. In the near future we will also have automatic creation of local PVs as described in [this design doc](https://github.com/openshift/enhancements/blob/master/enhancements/local-storage/automatic-detection.md)

**Comment by jarrpa** [comment]
As this is working as designed and we recommend adjusting to that design, I'll be closing this issue.
