### ISSUE TITLE
Something off - think we need to add OperatorSource yaml and make sure naming conventions are followed

### ISSUE THREAD

**Issue by screeley44** [openshift/ocs-operator#46]
Missing OperatorSource, not sure of the correct yaml to use, but should probably be something like this. It needs to point to the quay.io appregistry repo that is being used.

```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: ocs-catalogsource
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io
  registryNamespace: ocs-dev
  displayName: "OCS Catalog Source"
  publisher: "Red Hat"
```

currently, what we are seeing is we have a CatalogSource, OperatorGroup and Subscription Created, but what I think we are missing is the OperatorSource which ties the CatalogSourceConfig  to the CatalogSource.  I successfully went through this process to add the `AWS S3 Operator` into OCP and the process I followed and how to test this in OCP is on this readme.  https://github.com/yard-turkey/awss3operator 

*Current Issue:*
We are not getting the ocs-operator to show up in the Hub - and the CSV is never created - it just sits there and hangs. 

```
# oc logs catalog-operator-7f6cd5c4cb-hqckr -n openshift-operator-lifecycle-manager
time="2019-08-22T17:07:20Z" level=info msg="retrying openshift-storage"
E0822 17:07:20.766270       1 queueinformer_operator.go:186] Sync "openshift-storage" failed: {ocs-operator alpha  {ocs-catalogsource openshift-marketplace}} not found: CatalogSource {ocs-catalogsource openshift-marketplace} not found
time="2019-08-22T17:07:20Z" level=info msg="retrying openshift-storage"
```

```
[root@ip-10-0-30-4 ~]# oc get csv -n openshift-storage
No resources found.

[root@ip-10-0-30-4 ~]# oc get catalogsources --all-namespaces
NAMESPACE                              NAME                      NAME                          TYPE       PUBLISHER   AGE
openshift-marketplace                  certified-operators       Certified Operators           grpc       Red Hat     2d1h
openshift-marketplace                  community-operators       Community Operators           grpc       Red Hat     2d1h
openshift-marketplace                  local-storage-manifests   Local Storage Operator        grpc       Red Hat     139m
openshift-marketplace                  ocs-catalogsource         Openshift Container Storage   grpc       Red Hat     139m
openshift-marketplace                  redhat-operators          Red Hat Operators             grpc       Red Hat     2d1h
openshift-operator-lifecycle-manager   olm-operators             OLM Operators                 internal   Red Hat     2d1h

[root@ip-10-0-30-4 openshift]# oc logs ocs-catalogsource-xjswz -n openshift-marketplace
time="2019-08-22T16:57:37Z" level=info msg="serving registry" database=bundles.db port=50051

[root@ip-10-0-30-4 openshift]# oc get operatorgroups --all-namespaces
NAMESPACE                              NAME                              AGE
local-storage                          local-operator-group              165m
openshift-monitoring                   openshift-cluster-monitoring      2d1h
openshift-operator-lifecycle-manager   olm-operators                     2d1h
openshift-operators                    global-operators                  2d1h
openshift-storage                      openshift-storage-operatorgroup   165m

[root@ip-10-0-30-4 openshift]# oc logs ocs-catalogsource-xjswz -n openshift-marketplace
time="2019-08-22T16:57:37Z" level=info msg="serving registry" database=bundles.db port=50051

[root@ip-10-0-30-4 openshift]# oc get operatorgroups --all-namespaces
NAMESPACE                              NAME                              AGE
local-storage                          local-operator-group              165m
openshift-monitoring                   openshift-cluster-monitoring      2d1h
openshift-operator-lifecycle-manager   olm-operators                     2d1h
openshift-operators                    global-operators                  2d1h
openshift-storage                      openshift-storage-operatorgroup   165m

```
Additionally, no other events are generated, just nothing happens, and in the console when I look at the subscription, there is no CSV - it's not finding it or not pulling it down correctly, I suspect it's the OperatorSource that is causing this.

@jarrpa @kshlm

**Comment by kshlm** [comment]
This is an alternate way to add a CatalogSource to an OCP cluster. When adding an OperatorSource, it still ends up creating a CatalogSource for the marketplace. Instead we just directly create the CatalogSource our selves.

It shouldn't be matter how the CatalogSource was created for subscriptions to work and CSVs to be created.

One issue I think could be causing your problems with CSV no getting installed, is that OLM gives up trying to install the CSV into the namespace before the CatalogSource comes up. The deploy-manifest we have now, creates a subscription at the same time as the catalogsource. It takes a little while for the catalogsource image to be pulled down, the registry started, and the catalogsource to become available.

I'd like you to try to create a manual subscription once the catalog source is up.
- If you've already deployed using the deploy manifest, and don't have the CSV yet, delete the subscription, and recreate it. Either from the console or cli.
- Or you could delete the subcription manifest from the file before you deploy. Then wait for the ocs-catalog to become available, and then create the subscription.

**Comment by screeley44** [comment]
I created the subscription manually - same result - no CSV and it just hangs...I am not able to test installing directly from the console because the operator never shows up in the console. I did successfully take your files and create my own test operator based on them, I used operator-courier to validate and push to quay.io - I had to fix and add several things to the CSV which I can discuss with you. I'm curious, has anyone successfully installed this operator in OCP 4 using the latest code/packages and install instructions on the README? If you want to review my test CSV please take a look at https://github.com/yard-turkey/ocsoperator and my appregistry on quay.io is https://quay.io/application/screeley44/ocsoperator-registry

**Comment by umangachapagain** [comment]
@screeley44  I understand your point. I follow the same process as you do.

The process that OCS Operator README suggests is valid for OCP 4.2 and not 4.1 which is what I believe you are using.

Using OperatorSource makes it available on both 4.1 and 4.2.

**Comment by kshlm** [comment]
@screeley44 As @umangachapagain said, the CatalogSource method has only worked on 4.2. It doesn't work on 4.1. OCS is targeted for OCP-4.2 and beyond, so we expect all development and testing to also happen on OCP-4.2.

If you've been testing on 4.1, can you please test it on 4.2 and let us know if this is still a problem.

**Comment by umangachapagain** [comment]
We use CatalogSource directly instead of OperatorSource. OperatorSource will be deprecated soon.
