### ISSUE TITLE
only 1 active Cephfs MDS daemon per cluster

### ISSUE THREAD

**Issue by bengland2** [openshift/ocs-operator#471]
Under a heavy metadata-intensive workload, the 1 Cephfs MDS daemon supplied by OCS is not enough to keep up, particularly for all-SSD configurations.    For example, with 100 pods all doing renames (smallfile benchmark), we see [this from top -H](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ocp4/smfruns/smf-rename.png), showing that 1 thread is at 70% CPU consumption, meaning that it is reaching the limit of what that thread can do - it doesn't matter how many other CPU cores are idle if 1 thread is using up a whole core.   MDS developers made a decision early on not to try to parallelize within a single MDS, but to support scale with multiple MDS daemons.   

We need to do [what is suggested by Ceph documentation here.](https://docs.ceph.com/docs/master/cephfs/multimds/).    The default should be[ ActiveCount: 1](https://github.com/openshift/ocs-operator/blob/5c80ec5a02cbbfbdd510202cbe7b371d35cdc3f7/pkg/controller/storagecluster/initialization_reconciler.go#L418-L422), but today it's hardcoded, it should be possible for people to raise it if necessary, at least for testing purposes.   There are customers who use lots of small files or objects and expect this to work reasonably well.    Thanks -ben

**Comment by mykaul** [comment]
I think it'd be interesting to see if we can use Kube's autoscale feature, and perform it according to custom metrics we'll expose from the MDS. For example, the number of clients.

**Comment by bengland2** [comment]
great idea Yaniv, but also the number of Cephfs files is relevant.  If you only have a few hundred thousand files then you probably don't need it, but if you scale out Cephfs like we are planning to, with millions and tens of millions of files, its a matter of time before someone needs this.   There is a way, I think - the operator could edit CephFilesystem YAML to change the number of MDS servers (this is also a workaround, but not a stable one).
