### ISSUE TITLE
Handle internal server error in case of storageclass creation fails

### ISSUE THREAD

**Issue by Madhu-1** [openshift/ocs-operator#486]
looks like OCS operator is not handling the internal server or any other error for storage-class, pool, filesystem, creation. one example is
https://github.com/openshift/ocs-operator/blob/5c80ec5a02cbbfbdd510202cbe7b371d35cdc3f7/pkg/controller/storagecluster/initialization_reconciler.go#L36-L59

**Comment by Madhu-1** [comment]
CC @jarrpa

**Comment by sp98** [comment]
@Madhu-1 All the resource creation functions (like ensureStorageClass, ensureCephCluster, etc) have a common pattern of returning the error in case of any failure in `creation` or `update` of those resources.  The error is then update as conditions for the end user [here](https://github.com/openshift/ocs-operator/blob/17d2372e76126e01e33a1a853fad9a26417c02ce/pkg/controller/storagecluster/reconcile.go#L255-L266).

Is this what you are looking for ?

**Comment by Madhu-1** [comment]
@sp98 I might be missing something https://github.com/openshift/ocs-operator/blob/5c80ec5a02cbbfbdd510202cbe7b371d35cdc3f7/pkg/controller/storagecluster/initialization_reconciler.go#L33 will error from above code is returned if the error is other than `NotFound`?
