### ISSUE TITLE
CSV ocs-operator.v0.0.1 should be named just ocs-operator

### ISSUE THREAD

**Issue by petr-balogh** [openshift/ocs-operator#50]
I think that the operator name shouldn't contain the version inside its name if the version can be taken from version attribute here:
https://github.com/openshift/ocs-operator/blob/525734a3146d55d6125490d9e5acf03bed080f83/deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml#L917

I also see that the openshift OLM does not have version in the name:

```console
$ oc get csv --all-namespaces
NAMESPACE                              NAME            DISPLAY          VERSION   REPLACES   PHASE
openshift-operator-lifecycle-manager   packageserver   Package Server   0.11.0               Succeeded
```

It means that we can in our automation rely only on one name ocs-operator and not ocs-operator.v0.0.1 which after upgrade shouldn't change the name IMO.

**Comment by kshlm** [comment]
The name is an OLM convention. It's not something we set ourselves.

**Comment by petr-balogh** [comment]
Can you tell me reason or link to documentation or other place where this was described/decided? Maybe then I will more understand why version is in the name. How it will be with upgrades and so? The version will change in name? We will have another one olm for new version? Thanks

**Comment by umangachapagain** [comment]
CSV name is directly mapped to Package Name, so it must be the same in all cases. Without this, the OLM integration would break and OCS Operator wouldn't be available in the OperatorHub.

In case of Upgrade,  a new CSV would be created with name ocs-operator.v0.0.2. This new CSV would then be referenced in the Package spec. This is what tells OLM that upgrade is available.

**Comment by kshlm** [comment]
@petr-balogh The [build-your-csv][1] document for OLM, mentions that this is the naming scheme. The operator-sdk generator follows this scheme, and we're using this. The CSV itself, also has a version attribute in its spec. I'm not sure right now of its use.

[1]: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#csv-metadata

**Comment by petr-balogh** [comment]
OK, thanks for the clarification. Is there a way how we can get latest version of CSV/operator.  What will be the scenario/steps if we would like to install some specific build of OCS?   For example for testing upgrade of OCS from 4.2 to 4.3, how we can manage this via operator?  Thanks

**Comment by kshlm** [comment]
@petr-balogh The CSV will be published as a catalog, which bundles all previous versions of the csv. The catalog bundles stuff this way to ensure they have a clear upgrade path between versions. The operatorhub section of the console will make use of this information to show available updates for an operator.

The bundle that is published is also available in the repo at https://github.com/openshift/ocs-operator/tree/master/deploy/olm-catalog/ocs-operator. The is the actual catalog that will be published into operatorhub, and is currently being packaged in the custom catalogsource. Right now there is only one CSV version. You can expect that to be the case till the first OCS version is released officially. Thereafter, new CSVs will be added for subsequent versions of the product.

**Comment by petr-balogh** [comment]
@kshlm thanks a lot! This https://github.com/openshift/ocs-operator/blob/master/deploy/olm-catalog/ocs-operator/ocs-operator.package.yaml sounds very useful and we can take the version of current CSV from there. I will update our automation to consume this file to get that version.  I think that this issue can be closed now.
