### ISSUE TITLE
NooBaa is not working in independent mode

### ISSUE THREAD

**Issue by cloudbehl** [openshift/ocs-operator#552]
The bucket class is being rejected because default backing store is not created. So the Noobaa OBC's are not created.

**Comment by cloudbehl** [comment]
[noobaa-operator-8fd8566f8-t5shn-noobaa-operator.log](https://github.com/openshift/ocs-operator/files/4764537/noobaa-operator-8fd8566f8-t5shn-noobaa-operator.log)

**Comment by MeridianExplorer** [comment]
BZ raised - 
https://bugzilla.redhat.com/show_bug.cgi?id=1847875
