### ISSUE TITLE
noobaa-db-0 pod not coming up with custom labels. 

### ISSUE THREAD

**Issue by cloudbehl** [openshift/ocs-operator#553]
I tried the custom label thing. The CSI pods are respecting the labels but NooBaa remains in a pending state. 

I am getting this error in noobaa pod. 
```Conditions
TypeStatusUpdatedReasonMessage
PodScheduledFalse
Jun 9, 11:57 am
Unschedulable0/9 nodes are available: 9 node(s) didn't match node selector.
```

**StorageCluster.yaml**
```
apiVersion: v1
items:
- apiVersion: ocs.openshift.io/v1
  kind: StorageCluster
  metadata:
   name: ocs-independent-storagecluster
    namespace: openshift-storage
  spec:
    externalStorage:
      enable: true
    labelSelector:
      matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
    version: 4.5.0
```
Configmap - **rook-ceph-operator-config.yaml**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
  selfLink: /api/v1/namespaces/openshift-storage/configmaps/rook-ceph-operator-config
  uid: 4d771397-7670-4ed7-801f-32ae23c71df7
  resourceVersion: '560809'
  creationTimestamp: '2020-06-09T06:20:07Z'
data:
  CSI_PLUGIN_TOLERATIONS: |-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
  CSI_PROVISIONER_NODE_AFFINITY: node-role.kubernetes.io/worker
  CSI_PROVISIONER_TOLERATIONS: |-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
```

**Comment by obnoxxx** [comment]
Hmm, I think we need a section for placement of noobaa-db like the one for noobaa-core here: https://github.com/openshift/ocs-operator/blob/master/pkg/controller/defaults/placements.go#L208

I had expected all daemons without special treatment to pick up the "all" placement https://github.com/openshift/ocs-operator/blob/master/pkg/controller/defaults/placements.go#L15 , but that doesn't seem to happen. Maybe we need to make getPlacement fall back to "all" ? Or create specific entry for noobaa-db.

**Comment by anubhav-here** [comment]
@cloudbehl I think this works fine after the latest PR for labelSelector got merged. Correct me if i am wrong, I think this was happening due to ExternalCluster.

**Comment by cloudbehl** [comment]
@anubhav-here yes I think this issue is fixed. Can you put your PR link & close this one.
