### ISSUE TITLE
Refactor and add tests for platform detection.

### ISSUE THREAD

**Issue by rohantmp** [openshift/ocs-operator#562]
Investigate:
- can we stop detecting the platform and detect the required features instead?
  - Eg detect availability of S3/other-object-storage API that we want to use instead of RGW.

At the very least.
- improve unit tests
- improve naming
- `Platform` is less confusing than `CloudPlatform`
- instead of checking `isValidCloudPlatform` for skipping CephObjectStore, make a method like `shouldSkipCephObjectDeployment` that captures the list of platforms to skip on.
- fix functests

Disregard the suggestions in this issue if you find better solutions.

https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/platform_detection.go

**Comment by 16bce091** [comment]
https://github.com/openshift/ocs-operator/pull/616/files
