### ISSUE TITLE
Need end-to-end functional/integration test (happy path) for OCS

### ISSUE THREAD

**Issue by obnoxxx** [openshift/ocs-operator#61]
This repository needs most urgently an end-to-end test that tests the whole OCS system with (openshift,) ocs-operator, rook-ceph, noobaa, etc that should test the basic happy path at least:

- set it all up
- make sure basic functionality like provisioning some apps with PVCs from the generated storage classes, and using them, 
- deleting the PVCs
- destroying the setup again

This is highest priority so that we can catch regressions early.

**Comment by obnoxxx** [comment]
@jarrpa @kshlm @davidvossel others... FYI

**Comment by mykaul** [comment]
@obnoxxx  - @RazTamir has this functionality already - why can't we use their code and infra?

**Comment by obnoxxx** [comment]
@mykaul yes this is being taken into account. The infra: we use prow/openshift-ci. But the test cases can and should be shared.

**Comment by umangachapagain** [comment]
We have E2E tests up and running using OpenShift CI.
