### ISSUE TITLE
Logging errors in the ocs-operator pod logs

### ISSUE THREAD

**Issue by nbalacha** [openshift/ocs-operator#757]
There are several instances of the following in the ocs-operator logs.

`{"level":"dpanic","ts":"2020-09-08T14:45:48.614Z","logger":"controller_storagecluster","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":{"namespace":"openshift-storage","name":"ocs-metrics-exporter"},"stacktrace":"github.com/go-logr/zapr.handleFields\n\t/home/nibalach/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106\ngithub.com/go-logr/zapr.(*infoLogger).Info\n\t/home/nibalach/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:70\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.CreateOrUpdateServiceMonitor\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/exporter.go:158\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.(*ReconcileStorageCluster).enableMetricsExporter\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/exporter.go:36\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.(*ReconcileStorageCluster).Reconcile\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/reconcile.go:350\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
{"level":"info","ts":"2020-09-08T14:45:48.614Z","logger":"controller_storagecluster","msg":"reconciling metrics exporter service monitor %v"}`

The log.Info() call should either use structured log formats or use log.Info(fmt.Sprintf())  to get around this.

**Comment by jarrpa** [comment]
I believe this has been fixed.
