### ISSUE TITLE
Cluster deletion fails

### ISSUE THREAD

**Issue by kshlm** [openshift/ocs-operator#81]
Deleting a fully deployed StorageCluster fails. Deleting a StorageCluster marks the owned CephCluster for deletion. But the CephCluster is never deleted, and the Rook ceph pods and resources continue to run.

The rook-ceph operator logs the following error,

```
2019-09-03 09:52:25.883690 I | op-cluster: cluster openshift-storage has a deletion timestamp
2019-09-03 09:52:25.884772 E | op-cluster: failed finalizer for cluster. failed to get volume attachments for operator namespace openshift-storage: the server could not find the requested resource (get volumes.rook.io)
```

This is making it hard during development to reuse an OCP cluster.

**Comment by davidvossel** [comment]
to be clear, the cephcluster finalizer exists for a reason. force deleting it will likely cause issues. 

it's most likely there to prevent force deletion until the rook operator has the chance to gracefully shutdown daemons. Once the rook operator is done, the finalizer should be removed allowing the cephcluster to be deleted.

**Comment by travisn** [comment]
The operator does perform cleanup operations. Is the operator being stopped at the same time? If so it won't be able to perform the cleanup. If the operator is not being stopped, do its logs indicate the cleanup failed?

**Comment by kshlm** [comment]
@travisn the failure logs are in the description of this issue.

**Comment by travisn** [comment]
@kshlm ah thanks, i missed that. I've opened https://github.com/rook/rook/issues/3912 to get this fixed.
