### ISSUE TITLE
Does S3 compatible storage through Nooba supports Security Token Services?

### ISSUE THREAD

**Issue by anuj812** [openshift/ocs-operator#846]
Does S3 compatible storage through Nooba supports Security Token Service ?
We tried using aws sts commands  on OCS object storage on Openshift 4.5 but didn't get any sucess. We were looking to migrate from minio to ocs but seeems to be a problem as it doesn't seems to be supporting STS .  We tried from AWS Java sdk as well as aws cli as well 'aws sts' commands. Please confirm.

**Comment by jarrpa** [comment]
This is not the right place for this question. You should probably head over to the noobaa project. https://github.com/noobaa/
