### ISSUE TITLE
OCS 4.7 multus - rbd command fails in toolbox pod

### ISSUE THREAD

**Issue by bengland2** [openshift/ocs-operator#866]
Is this the right place for this issue?   With multus enabled, running ocs-operator.4.7.0-139.ci , I can't seem to look at some of Ceph state with toolbox pod.   The cluster comes up fine, but some toolbox commands work and some don't.   
```
[kni@e26-h13-740xd ocs-bringup]$ oc -n openshift-storage rsh rook-ceph-tools-8646ddfd7-ptnvq 
sh-4.4# rbd ls -p ocs-storagecluster-cephblockpool
2020-10-23 16:50:04.665 7f3928d73700 -1 set_mon_vals failed to set cluster_network = 192.168.232.0/24: Configuration option 'cluster_network' may not be modified at runtime
2020-10-23 16:50:04.665 7f3928d73700 -1 set_mon_vals failed to set public_network = 192.168.231.0/24: Configuration option 'public_network' may not be modified at runtime
2020-10-23 16:50:04.666 7f3913fff700 -1 set_mon_vals failed to set cluster_network = 192.168.232.0/24: Configuration option 'cluster_network' may not be modified at runtime
2020-10-23 16:50:04.666 7f3913fff700 -1 set_mon_vals failed to set public_network = 192.168.231.0/24: Configuration option 'public_network' may not be modified at runtime
```
When I look at the network, I see that it is more like host networking than multus networking, shouldn't it have the same networking setup as other OCS pods and the annotations for Multus so that it can talk to OSDs, etc?
```
[kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-tools-8646ddfd7-ptnvq 
sh-4.4# grep -v veth /proc/net/dev 
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eno3: 21694276  127158    0    0    0     0          0     25907    54610     635    0    0    0     0       0          0
  eno1: 3275916   24897    0    0    0     0          0     48947  1946464   10494    0    0    0     0       0          0
  eno4:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
ens7f0: 4683590815884 3401505593    0 25182    0     0          0    867297 3848810455120 2885322473    0    0    0     0       0          0
  eno2: 2549808   41829    0    0    0     0          0     43783    48014     505    0    0    0     0       0          0
    lo: 10518947426 67339941    0    0    0     0          0         0 10518947426 67339941    0    0    0     0       0          0
ens7f1: 67412423  103750    0    0    0     0          0      3997 66768212  101337    0    0    0     0       0          0
   br0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  tun0: 3472895102621 257437509    0    0    0     0          0         0 666814287404 251824350    0    0    0     0       0          0
ovs-system:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
vxlan_sys_4789: 4281927097008 528150537    0    0    0     0          0         0 3489962356908 444733322    0    0    0     0       0          0
```
whereas an OSD pod looks like this:
```
[kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-[osd-4](https://issues.redhat.com/browse/osd-4)-7f66889dc9-t67sv 
sh-4.4# more /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  net2: 22614417   24339    0    0    0     0          0       215 22394835   21561    0    0    0     0       0          0
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:  247557    2253    0    0    0     0          0         0 10641491    2384    0    0    0     0       0          0
  net1: 24610072   27604    0    0    0     0          0        77 24428567   24932    0    0    0     0       0          0
```

and the ceph.conf is only enough to let it talk to mons, nothing else:
```
[kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-tools-8646ddfd7-ptnvq 
sh-4.4# more /etc/ceph/ceph.conf 
[global]
mon_host = 172.30.15.128:6789,172.30.158.53:6789,172.30.172.195:6789

[client.admin]
keyring = /etc/ceph/keyring
```

**Comment by rohan47** [comment]
The CSI fix for the RBD command https://github.com/ceph/ceph-csi/pull/1450 is not merged yet so it will fail for now.

**Comment by rohan47** [comment]
Can you share the StorageCluster CR?

**Comment by rohan47** [comment]
Also, https://github.com/ceph/ceph-csi/pull/1450 is not yet merged. So CSI RBD plugin won't work.

**Comment by rohan47** [comment]
> When I look at the network, I see that it is more like host networking than multus networking, shouldn't it have the same networking setup as other OCS pods and the annotations for Multus so that it can talk to OSDs, etc?
> 
> ```
> [kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-tools-8646ddfd7-ptnvq 
> sh-4.4# grep -v veth /proc/net/dev 
> Inter-|   Receive                                                |  Transmit
>  face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
>   eno3: 21694276  127158    0    0    0     0          0     25907    54610     635    0    0    0     0       0          0
>   eno1: 3275916   24897    0    0    0     0          0     48947  1946464   10494    0    0    0     0       0          0
>   eno4:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
> ens7f0: 4683590815884 3401505593    0 25182    0     0          0    867297 3848810455120 2885322473    0    0    0     0       0          0
>   eno2: 2549808   41829    0    0    0     0          0     43783    48014     505    0    0    0     0       0          0
>     lo: 10518947426 67339941    0    0    0     0          0         0 10518947426 67339941    0    0    0     0       0          0
> ens7f1: 67412423  103750    0    0    0     0          0      3997 66768212  101337    0    0    0     0       0          0
>    br0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
>   tun0: 3472895102621 257437509    0    0    0     0          0         0 666814287404 251824350    0    0    0     0       0          0
> ovs-system:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
> vxlan_sys_4789: 4281927097008 528150537    0    0    0     0          0         0 3489962356908 444733322    0    0    0     0       0          0
> ```
> 
Is the toolbox pod using Multus?
Multus interfaces normally are named `net1`/`net2`

> whereas an OSD pod looks like this:
> 
> ```
> [kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-[osd-4](https://issues.redhat.com/browse/osd-4)-7f66889dc9-t67sv 
> sh-4.4# more /proc/net/dev
> Inter-|   Receive                                                |  Transmit
>  face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
>   net2: 22614417   24339    0    0    0     0          0       215 22394835   21561    0    0    0     0       0          0
>     lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
>   eth0:  247557    2253    0    0    0     0          0         0 10641491    2384    0    0    0     0       0          0
>   net1: 24610072   27604    0    0    0     0          0        77 24428567   24932    0    0    0     0       0          0
> ```
> 
So the OSD pods are using Multus network, right?

> and the ceph.conf is only enough to let it talk to mons, nothing else:
> 
> ```
> [kni@e26-h13-740xd ocs-bringup]$ ocos rsh rook-ceph-tools-8646ddfd7-ptnvq 
> sh-4.4# more /etc/ceph/ceph.conf 
> [global]
> mon_host = 172.30.15.128:6789,172.30.158.53:6789,172.30.172.195:6789
> 
> [client.admin]
> keyring = /etc/ceph/keyring
> ```
As per this https://github.com/rook/rook/issues/6313#issuecomment-699895337 comment, it looks correct.

**Comment by jarrpa** [comment]
You should open a BZ against OCS, using the rook component.
