### ISSUE TITLE
ocs4.5 UI: Storageclass select dropdown didn't contain all the sc

### ISSUE THREAD

**Issue by LeslieKuo** [openshift/ocs-operator#873]
This issue is parallel with issue https://github.com/openshift/ocs-operator/issues/869 
I think maybe there's something wrong with the ocs backend.
Env info:
```
-inf:~ # oc version
Client Version: 4.3.13
Server Version: 4.3.13
Kubernetes Version: v1.16.2
-inf:~ # oc get csv -n openshift-storage
NAME                  DISPLAY                       VERSION   REPLACES   PHASE
ocs-operator.v4.5.1   OpenShift Container Storage   4.5.1                Succeeded
```

Check storageclass in cli:
```
-inf:~ # oc get sc
NAME                                 PROVISIONER                     AGE
rook-ceph-block-internal (default)   rook-ceph.rbd.csi.ceph.com      5h31m
rook-ceph-cephfs-internal            rook-ceph.cephfs.csi.ceph.com   5h31m
rook-ceph-delete-bucket-internal     ceph.rook.io/bucket             5h31m
```
Actually there are three cs available in cluster.
But there is only one sc visibel in the UI dropdown list.
![image](https://user-images.githubusercontent.com/18239311/97450842-1be4ab80-196e-11eb-9ad4-2b0e1c0deac2.png)
So I want to know if there is any rules for ocs storageclass such as special labels?
Thanks a lot.

**Comment by umangachapagain** [comment]
cc @bipuladh

**Comment by bipuladh** [comment]
The UI does not list any storage classes that are provisioned by Rook, unfortunately, we missed `ceph.rook.io/bucket`(this should not be shown as well). 
We filter and show storage classes that can be used to create a storage class. Hence, we filter out rook-ceph storage classes. Looks like this is a bare-metal cluster as an infrastructure-based provisioner is not shown. 
We will fix this behaviour and hide `ceph.rook.io/bucket` based classes as well.
