### ISSUE TITLE
Ensure that the CephPools have their failure domain as "zone".

### ISSUE THREAD

**Issue by rohantmp** [openshift/ocs-operator#88]
Some lines that show host is currently being used: 
- https://github.com/openshift/ocs-operator/blob/6db54df094f6a9bfab35f172628725a9ce0f542a/pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go#L419
- https://github.com/openshift/ocs-operator/blob/6db54df094f6a9bfab35f172628725a9ce0f542a/pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go#L516

**Comment by rohantmp** [comment]
@jarrpa who's in charge of initialization?

**Comment by jarrpa** [comment]
No one? Whoever has the bandwidth to take it up.

**Comment by rohantmp** [comment]
Resolved by PR #95

**Comment by obnoxxx** [comment]
@rohantmp @kshlm @jarrpa @travisn @davidvossel - I am not sure that unconditionally setting the failure domain to zone is actually correct: What if we want replica-3 and we don't have 3 zones? ... Wouldn't this fail? I think in AWS we have zones, that map to AZs, but some regions have less than 3 zones. What to do there? And what if OCP has only been set up with nodes in less than 3 zones? Or if the admin has not chosen/labeled/tainted nodes from 3 AZs for storage? And what if we don't have zones at all? ...

Another aspect is why the e2e CI job has succeeded. Is it using 3 zones, @davidvossel ? (I don't think so...) I can only guess that pool creation still succeeds, but that creation of objects would fail. We currently only deploy, tests that create PVs are yet to come. :-)

I think we need to revisit this and refine the work of  PR #95....

**Comment by obnoxxx** [comment]
FYI, I proposed PR #106 to revert the zone change for now, as it is breaking setups (that don't have zones, etc....)

**Comment by rohantmp** [comment]
Closing this and opening Issue #107

**Comment by obnoxxx** [comment]
@rohantmp 
> Closing this and opening Issue #107
This is not closed. ;-)
