### ISSUE TITLE
OpenShift Container Storage Operator support for ppc64le architecture

### ISSUE THREAD

**Issue by ticlazau** [openshift/ocs-operator#928]
Hello,

has anyone successfully install OpenShift Container Storage Operator on OCP 4.x? I see no reference to ppc64le architecture.
Looking forward.

Rgds,
FM

**Comment by obnoxxx** [comment]
Hi, thanks for asking!

Red Hat is going to support power in the product soon, but we're not building and testing for power here in the upstream repo.

**Comment by ticlazau** [comment]
Thank you @obnoxxx this is good news. Do you have any outlook on how "soon" will be - 6m or 1y?
I will be interested on a beta or early adopter program if available.

Rgds,
FM

**Comment by jarrpa** [comment]
Any official support statements and roadmaps for the product will be delivered via the official company channels. Keep an eye on Red Hat blogs and announcements for the latest details. Since I see you've contributed to IBM projects, you may have better luck asking some of their teams.

**Comment by ticlazau** [comment]
Thank you
