### ISSUE TITLE
Do you support the openPower architecture 

### ISSUE THREAD

**Issue by it2911** [openshift/ocs-operator#957]
I want to use the Openshfit Container Storage platform. I found the ocs-operator can easily deploy a storage cluster for me. Do you support the openPower architecture?

**Comment by mykaul** [comment]
'support' is a big statement. The OCS-operator can certainly be compiled and run on Power.

**Comment by jarrpa** [comment]
We have no upstream testing on Power at this time. Official support statements will come through official Red Hat channels, in the form of release notes and official Red Hat blogs.
