### ISSUE TITLE
Need to update CSV, cluster generation, and CephCluster Spec when rook releases the next image.

### ISSUE THREAD

**Issue by rohantmp** [openshift/ocs-operator#99]
- Enable fencing controller via env var and CephCluster Spec
   - https://github.com/rook/rook/pull/3715
 - Disable CephNFS controller via env var.
   - https://github.com/rook/rook/pull/3794

**Comment by umangachapagain** [comment]
We update versions for each release and update CSV whenever required.
I believe that is the expectation of this issue.
